spring:
  application:
    name: "api-gateway"
#  cloud:
#    gateway:
#      routes:
#        - id: baeldung
#          uri: baeldung.com
#          predicates:
#            - Path=/baeldung/
#        - id: myOtherRouting
#          uri: localhost:9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}


